USE [master]
GO

/****** Object:  Database [dbPerson]    Script Date: 7.12.2021 20:57:24 ******/
CREATE DATABASE [dbPerson]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbPerson', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbPerson.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbPerson_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbPerson_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbPerson].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbPerson] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbPerson] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbPerson] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbPerson] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbPerson] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbPerson] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbPerson] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbPerson] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbPerson] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbPerson] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbPerson] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbPerson] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbPerson] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbPerson] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbPerson] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbPerson] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbPerson] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbPerson] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbPerson] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbPerson] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbPerson] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbPerson] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbPerson] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbPerson] SET  MULTI_USER 
GO

ALTER DATABASE [dbPerson] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbPerson] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbPerson] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbPerson] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbPerson] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbPerson] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dbPerson] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbPerson] SET  READ_WRITE 
GO

